import { AccountType } from 'oldschooljs/dist/meta/types'
import Player from 'oldschooljs/dist/structures/Player'

export function genericPlayer(): Player {
	return new Player({
		username: 'username',
		skills: {
			overall: { rank: -1, level: 23, xp: 0 },
			attack: { rank: -1, level: 1, xp: 0 },
			defence: { rank: -1, level: 1, xp: 0 },
			strength: { rank: -1, level: 1, xp: 0 },
			hitpoints: { rank: -1, level: 1, xp: 0 },
			ranged: { rank: -1, level: 1, xp: 0 },
			prayer: { rank: -1, level: 1, xp: 0 },
			magic: { rank: -1, level: 1, xp: 0 },
			cooking: { rank: -1, level: 1, xp: 0 },
			woodcutting: { rank: -1, level: 1, xp: 0 },
			fletching: { rank: -1, level: 1, xp: 0 },
			fishing: { rank: -1, level: 1, xp: 0 },
			firemaking: { rank: -1, level: 1, xp: 0 },
			crafting: { rank: -1, level: 1, xp: 0 },
			smithing: { rank: -1, level: 1, xp: 0 },
			mining: { rank: -1, level: 1, xp: 0 },
			herblore: { rank: -1, level: 1, xp: 0 },
			agility: { rank: -1, level: 1, xp: 0 },
			thieving: { rank: -1, level: 1, xp: 0 },
			slayer: { rank: -1, level: 1, xp: 0 },
			farming: { rank: -1, level: 1, xp: 0 },
			runecraft: { rank: -1, level: 1, xp: 0 },
			hunter: { rank: -1, level: 1, xp: 0 },
			construction: { rank: -1, level: 1, xp: 0 }
		},
		minigames: {
			bountyHunter: { rank: -1, score: -1 },
			bountyHunterRogue: { rank: -1, score: -1 },
			LMS: { rank: -1, score: -1 }
		},
		bossRecords: {
			abyssalSire: { rank: -1, score: -1 },
			alchemicalHydra: { rank: -1, score: -1 },
			barrowsChests: { rank: -1, score: -1 },
			bryophyta: { rank: -1, score: -1 },
			callisto: { rank: -1, score: -1 },
			cerberus: { rank: -1, score: -1 },
			chambersofXeric: { rank: -1, score: -1 },
			chambersofXericChallengeMode: { rank: -1, score: -1 },
			chaosElemental: { rank: -1, score: -1 },
			chaosFanatic: { rank: -1, score: -1 },
			commanderZilyana: { rank: -1, score: -1 },
			corporealBeast: { rank: -1, score: -1 },
			crazyArchaeologist: { rank: -1, score: -1 },
			dagannothPrime: { rank: -1, score: -1 },
			dagannothRex: { rank: -1, score: -1 },
			dagannothSupreme: { rank: -1, score: -1 },
			derangedArchaeologist: { rank: -1, score: -1 },
			generalGraardor: { rank: -1, score: -1 },
			giantMole: { rank: -1, score: -1 },
			grotesqueGuardians: { rank: -1, score: -1 },
			hespori: { rank: -1, score: -1 },
			kalphiteQueen: { rank: -1, score: -1 },
			kingBlackDragon: { rank: -1, score: -1 },
			kraken: { rank: -1, score: -1 },
			kreeArra: { rank: -1, score: -1 },
			krilTsutsaroth: { rank: -1, score: -1 },
			mimic: { rank: -1, score: -1 },
			nightmare: { rank: -1, score: -1 },
			obor: { rank: -1, score: -1 },
			sarachnis: { rank: -1, score: -1 },
			scorpia: { rank: -1, score: -1 },
			skotizo: { rank: -1, score: -1 },
			theGauntlet: { rank: -1, score: -1 },
			theCorruptedGauntlet: { rank: -1, score: -1 },
			theatreofBlood: { rank: -1, score: -1 },
			thermonuclearSmokeDevil: { rank: -1, score: -1 },
			tzKalZuk: { rank: -1, score: -1 },
			tzTokJad: { rank: -1, score: -1 },
			venenatis: { rank: -1, score: -1 },
			vetion: { rank: -1, score: -1 },
			vorkath: { rank: -1, score: -1 },
			wintertodt: { rank: -1, score: -1 },
			zalcano: { rank: -1, score: -1 },
			zulrah: { rank: -1, score: -1 }
		},
		type: AccountType.Normal,
		clues: {
			all: { rank: -1, score: -1 },
			beginner: { rank: -1, score: -1 },
			easy: { rank: -1, score: -1 },
			medium: { rank: -1, score: -1 },
			hard: { rank: -1, score: -1 },
			elite: { rank: -1, score: -1 },
			master: { rank: -1, score: -1 }
		}
	})
}
